# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/image_to_pointcloud',
                'doc_host': 'https://AIR-UFG.github.io',
                'git_url': 'https://github.com/AIR-UFG/image_to_pointcloud',
                'lib_path': 'image_to_pointcloud'},
  'syms': {'image_to_pointcloud.core': {'image_to_pointcloud.core.foo': ('core.html#foo', 'image_to_pointcloud/core.py')}}}
